import React, { useEffect, useState } from 'react';
import { CheckCircle2, ShieldCheck, TriangleAlert } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../lib/api.js';
import { useAuth } from '../context/AuthContext.jsx';
import Toast from '../components/Toast.jsx';
import { useToast } from '../hooks/useToast.js';

const LEVEL_BADGE = { warning: 'badge-warning', critical: 'badge-critical' };

export default function AlertsPage() {
  const { user } = useAuth();
  const { toast, showToast, hideToast } = useToast();
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('unresolved');

  const canResolve = ['admin', 'technician'].includes(user?.role);
  const isAdmin = user?.role === 'admin';

  async function load() {
    try {
      const params = new URLSearchParams();
      if (filter === 'unresolved') params.set('resolved', 'false');
      if (filter === 'resolved') params.set('resolved', 'true');
      const res = await apiRequest(`/api/alerts?${params}`);
      setAlerts(res.data || []);
    } catch (err) { showToast(err.message, 'error'); }
    finally { setLoading(false); }
  }

  useEffect(() => { load(); }, [filter]);

  async function handleResolve(alert) {
    try {
      await apiRequest(`/api/alerts/${alert.id}/resolve`, { method: 'PATCH' });
      showToast('Alert resolved'); load();
    } catch (err) { showToast(err.message, 'error'); }
  }

  async function handleDelete(alert) {
    if (!confirm('Delete this alert?')) return;
    try {
      await apiRequest(`/api/alerts/${alert.id}`, { method: 'DELETE' });
      showToast('Alert deleted'); load();
    } catch (err) { showToast(err.message, 'error'); }
  }

  return (
    <div className="space-y-6">
      {toast && <Toast message={toast.message} type={toast.type} onClose={hideToast} />}
      <div>
        <h1 className="page-title">Alerts</h1>
        <p className="page-subtitle">{alerts.length} alerts · auto-generated by risk engine</p>
      </div>

      {/* Filter tabs */}
      <div style={{ display: 'flex', gap: 8 }}>
        {['unresolved', 'resolved', 'all'].map(f => (
          <button key={f} onClick={() => setFilter(f)}
            style={{
              padding: '6px 16px', borderRadius: 10, fontSize: 13, fontWeight: 600,
              background: filter === f ? 'rgba(34,211,238,0.15)' : 'rgba(255,255,255,0.04)',
              color: filter === f ? '#22d3ee' : 'var(--text-muted)',
              border: filter === f ? '1px solid rgba(34,211,238,0.30)' : '1px solid rgba(255,255,255,0.07)',
              cursor: 'pointer', textTransform: 'capitalize', transition: 'all 0.15s',
            }}>{f}</button>
        ))}
      </div>

      {loading ? (
        <div style={{ display: 'flex', justifyContent: 'center', paddingTop: 80 }}><div className="loading-spinner w-8 h-8" /></div>
      ) : alerts.length === 0 ? (
        <div className="empty-state card">
          <CheckCircle2 size={40} className="empty-state-icon" style={{ marginBottom: 12 }} />
          <p style={{ color: '#e2e8f0', fontWeight: 700, marginBottom: 4 }}>No alerts</p>
          <p style={{ color: 'var(--text-muted)', fontSize: 13 }}>All equipment is operating within safe parameters</p>
        </div>
      ) : (
        <div className="grid sm:grid-cols-2 gap-4">
          {alerts.map(alert => (
            <div key={alert.id} className="card" style={{
              borderLeft: `3px solid ${alert.level === 'critical' ? '#f87171' : '#fbbf24'}`,
              opacity: alert.resolved ? 0.65 : 1,
            }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                    <span className={LEVEL_BADGE[alert.level]}>{alert.level}</span>
                    {alert.resolved && <span className="badge-healthy">Resolved</span>}
                  </div>
                  <p style={{ fontWeight: 600, color: '#e2e8f0', fontSize: 13 }}>{alert.equipmentName}</p>
                  <p style={{ color: 'var(--text-muted)', fontSize: 12, marginTop: 4, lineHeight: 1.6 }}>{alert.message}</p>
                  <div style={{ display: 'flex', gap: 16, marginTop: 10, fontSize: 12, color: 'var(--text-muted)' }}>
                    <span>Risk: <strong style={{ color: '#e2e8f0' }}>{alert.riskScore}%</strong></span>
                    <span>Maintenance window: <strong style={{ color: '#e2e8f0' }}>{alert.predictedDaysToFailure}d</strong></span>
                  </div>
                  {alert.resolved && alert.resolvedAt && (
                    <p style={{ fontSize: 11, color: 'var(--text-soft)', marginTop: 8 }}>
                      Resolved {new Date(alert.resolvedAt).toLocaleDateString()}
                    </p>
                  )}
                  <div style={{ marginTop: 8 }}>
                    <Link to="/dashboard/records" style={{ fontSize: 11, color: '#22d3ee', textDecoration: 'none' }}>
                      View in Records →
                    </Link>
                  </div>
                </div>
              </div>
              {((!alert.resolved && canResolve) || isAdmin) && (
                <div style={{ display: 'flex', gap: 8, marginTop: 16, paddingTop: 14, borderTop: '1px solid rgba(255,255,255,0.07)' }}>
                  {!alert.resolved && canResolve && (
                    <button onClick={() => handleResolve(alert)} className="btn-success" style={{ fontSize: 12, padding: '6px 12px' }}>
                      <CheckCircle2 size={13} /> Resolve
                    </button>
                  )}
                  {isAdmin && (
                    <button onClick={() => handleDelete(alert)} className="btn-danger" style={{ fontSize: 12, padding: '6px 12px' }}>Delete</button>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
